[parity]
chain = "/root/parity/chain.json"

base_path = "/root/parity"

[account]
unlock = ["0x00a054ffda97220e9a7483e6e7b87d445e4d6c96"]
password = ["/root/parity/keys/Torvalds/.passphrase"]

[ui]
force = false
disable = false
port = 8180
interface = "0.0.0.0"

[rpc]
interface = "0.0.0.0"
cors = "*"
disable = false
port = 8545
apis = ["web3", "eth", "net", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
hosts = ["all"]

[websockets]
disable = false
port = 8546
interface = "local"
origins = ["*"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["all"]

[ipc]
disable = false
apis = ["web3", "eth", "net", "parity", "parity_accounts", "personal", "traces", "rpc", "secretstore"]


[ipfs]
interface = "0.0.0.0"
cors = "*"

[network]
port = 30303
min_peers = 25
max_peers = 50
nat = "any"
id = 9
bootnodes = []
discovery = true
warp = true
allow_ips = "all"
snapshot_peers = 0
max_pending_peers = 64
no_serve_light = false
reserved_only = false

[mining]
engine_signer = "0x00a054ffda97220e9a7483e6e7b87d445e4d6c96"
reseal_on_txs = "none"
reseal_min_period = 0
usd_per_tx = "0"
